Sprint 1, increment 2 (unit tests)
eridiumdev/yandex-praktikum-go-devops pull request #2
Opened 2022-06-21 08:06 UTC by eridiumdev

2022-07-05 17:33 UTC, rktkov requested changes
Я код читал снизу вверх. От internal/metrics  до agent. Соотвественно комментарии тоже стоит читать в этой же последовательности, так как более поздние ссылаются на более ранние.

2022-07-05 17:33 UTC, rktkov commented on internal/metrics/metric.go
> +	Name string
Почему поле класса является обще доступном, если у нас предусмотрен метод получения его значения в интерфейсе. С точки зрения ГО это дублирования функционала. Либо делать поле закрытым, либо убирать метод из интерфейса.

2022-07-05 17:33 UTC, rktkov commented on internal/metrics/metric.go
> +type Metric interface {
Согласно рекомендация ГО сообщества, названия интерфейсов должны отражать их функциональную суть (Reader, Writer, Caller и т.д). В вашем случае интерфейс получатель, поэтому его и стоит так назвать.

2022-07-05 17:33 UTC, rktkov commented on internal/metrics/gauge.go
> +	Value Gauge
Тот же комментарий, что и с полем Name в типе AbstractMetric.

2022-07-05 17:33 UTC, rktkov commented on internal/metrics/counter.go
> +	Value Counter
см. Gauge

2022-07-05 17:33 UTC, rktkov commented on internal/logger/logger.go
> +	"log"
Лучше сразу использовать более оптимальные логеры, например zerolog.

2022-07-05 17:33 UTC, rktkov commented on internal/logger/logger.go
> +var l *Logger
Названия переменных, полей длинной в 1 символ очень сильно усложняют чтение кода. Старайтесь давать более developer friendly имена.

2022-07-05 17:33 UTC, rktkov commented on cmd/server/storage/storage.go
> +type Storage interface {
см. комментарий про имена интерфейсов в AbstractMetric

2022-07-05 17:33 UTC, rktkov commented on cmd/server/storage/in-mem.go
> +import (
Возьмите в привычку сортировать импортируемые пакеты следующим образом:
1. пакеты стандартной библиотеки
2. внешние установленные пакеты
3. внутренние пакеты проекта

Для того, чтобы разные автоматические инструменты из не пересортировывали, разделяйте блоки пустой строкой.

2022-07-05 17:33 UTC, rktkov commented on cmd/server/storage/in-mem.go
> +func (st *InMemStorage) StoreMetric(metric metrics.Metric) error {
Метод всегда будет возвращать пустую ошибку. С точки зрения языка ГО это является избыточной логикой. Если вы в данный момент не возвращаете ошибку, то стоит убрать из сигнатуры метода указание на ошибку как результат  работы метода. Конечно, скорее всего вы предпологаете, что когда в будущем у вас будет другая логика работы, которая будет подразумевать наличие ошибка. Вот в момент времени, когда вы эту логику начнете реализовывать, тогда и добавьте указание на возвращаемое значение. А пока "мертвые хвосты" лучше отрубить.

2022-07-05 17:33 UTC, rktkov commented on cmd/server/storage/storage.go
> +	GetMetric(metricType, metricName string) (metrics.Metric, error)
А зачем нам указывать тип метрики в методе получения. У нас возможна ситуация, что будет 2 метрики с одинаковым именем, но разными типами? Такого в ТЗ не сказано, а значит не надо добавлять лишнюю логику от себя в систему хранения.

2022-07-05 17:33 UTC, rktkov commented on cmd/server/storage/in-mem.go
> +func (st *InMemStorage) GetMetric(metricType, metricName string) (metrics.Metric, error) {
Измениться интерфейс, изменится логика работы метода. И я бы еще подумал, о том, стоит ли возвращать именно ошибку как указатель на то, что метрики не существует. Поведение вашего типа очень похоже на поведение стандартной мапы, может не стоит предлагать новый вариант поведения в привычной для большинства разработчиков ситуации и вернуть не ошибку а флаг?

2022-07-05 17:33 UTC, rktkov commented on cmd/server/storage/in-mem.go
> +func (st *InMemStorage) ListMetrics() ([]metrics.Metric, error) {
см. комментарий по поводу err выше

2022-07-05 17:33 UTC, rktkov commented on cmd/server/rendering/html.go
> +import (
см. комментарий про порядок импорта

2022-07-05 17:33 UTC, rktkov commented on cmd/server/rendering/html.go
> +func NewHTMLEngine(tplDir string) *HTMLEngine {
А может стоит себя обезопасить и проверить существования папки, чтобы дальше не было мучительно больно.

2022-07-05 17:33 UTC, rktkov commented on cmd/server/rendering/engine.go
> +type Engine interface {
Название интерфейса.

2022-07-05 17:33 UTC, rktkov commented on cmd/server/http/server.go
> +import (
см. комментарий про порядок импорта

2022-07-05 17:33 UTC, rktkov commented on cmd/server/http/server.go
> +func NewServer(router routers.Router, host string, port int, ) *Server {
А что если строка пустая?

2022-07-05 17:33 UTC, rktkov commented on cmd/server/main.go
> +import (
см. комментарий про порядок импорта

2022-07-05 17:33 UTC, rktkov commented on cmd/server/http/handlers/handler.go
> +import (
см. комментарий про порядок импорта

2022-07-05 17:33 UTC, rktkov commented on cmd/server/http/handlers/metrics.go
> +import (
см. комментарий про порядок импорта

2022-07-05 17:33 UTC, rktkov commented on cmd/server/http/handlers/metrics.go
> +	metric, err := h.Store.GetMetric(metricType, metricName)
выше в методе изменения метрики, ведь происходит на уровне обработчика анализ типа метрики, почему бы  это и не сделать здесь, а хранилище уже обращаться только по имени метрики.

2022-07-05 17:33 UTC, rktkov commented on cmd/agent/collectors/collector.go
> +type Collector interface {
Интерфейс отличается от экспортера только 1 методом. Может  быть вынести общий для обоих интерфейсов код в базовый "исполнитель" и уже потом реализовывать в каждом специфическую логику?

2022-07-05 17:33 UTC, rktkov commented on cmd/agent/collectors/collector.go
> +import (
см. комментарий про порядок импорта

2022-07-05 17:33 UTC, rktkov commented on cmd/agent/collectors/poll-count.go
> +import (
см. комментарий про порядок импорта

2022-07-05 17:33 UTC, rktkov commented on cmd/agent/collectors/random.go
> +import (
см. комментарий про порядок импорта

2022-07-05 17:33 UTC, rktkov commented on cmd/agent/collectors/runtime.go
> +import (
см. комментарий про порядок импорта

2022-07-05 17:33 UTC, rktkov commented on cmd/agent/exporters/http.go
> +import (
см. комментарий про порядок импорта

2022-07-05 17:33 UTC, rktkov commented on cmd/agent/exporters/exporter.go
> +import (
см. комментарий про порядок импорта

2022-07-05 17:33 UTC, rktkov commented on cmd/agent/exporters/log.go
> +import (
см. комментарий про порядок импорта

2022-07-05 17:33 UTC, rktkov commented on cmd/agent/main.go
> +import (
см. комментарий про порядок импорта

2022-07-05 17:33 UTC, rktkov commented on cmd/agent/agent.go
> +import (
см. комментарий про порядок импорта

2022-07-05 19:27 UTC, bambruysk reviewed
Стоит продумать архитектуру и логику работы агента.
В целом работа проделана большая, и некоторые фичи реализованы даже вне задания, это плюс, но впереди еще много инкрементов. Так держать.

2022-07-05 19:27 UTC, bambruysk commented on cmd/agent/agent.go
> +	collectInterval time.Duration
хорошей практикой будет вывести эти параметры в отдельную структуру Options

2022-07-05 19:27 UTC, bambruysk commented on cmd/agent/agent.go
> +func NewAgent(collectInterval time.Duration, exportInterval time.Duration) *Agent {
Общее замечание: прогнть через линтер golangci-lint. в частности экспортируемые фукнции должны быть откомментированы

2022-07-05 19:27 UTC, bambruysk commented on cmd/agent/agent.go
> +	flushMetricsBuffer chan interface{}
Если данные в этом канале не используются то лучше использовать chan struct{}

2022-07-05 19:27 UTC, bambruysk commented on internal/metrics/metric.go
> +	GetName() string
Более гошный стиль - не использовать Get префикс.

2022-07-05 19:27 UTC, bambruysk commented on internal/metrics/gauge.go
> +func (m GaugeMetric) GetValue() interface{} {
Возвращать из функции пустой интерфейс не очень хорошо. Это нарушает типизацию, да и вообще не очень  то принято.

2022-07-05 19:27 UTC, bambruysk commented on cmd/agent/agent.go
> +		metricsChannel:     make(chan metrics.Metric),
Почему не использоваать буферизированный канал?  Это кажется узким местом весьма.

2022-07-05 19:27 UTC, bambruysk commented on cmd/agent/agent.go
> +				if m.GetName() == metric.GetName() {
Здесь явно нарпашивается использование map

2022-07-05 19:27 UTC, bambruysk commented on cmd/agent/agent.go
> +				go a.collectMetrics(ctx, col)
выглядит не совсем потокобезопасно.

2022-07-05 19:27 UTC, bambruysk commented on cmd/server/http/handlers/handler.go
> +func (h *AbstractHandler) RenderHTML(w http.ResponseWriter, status int, body []byte) {
А зачем в этой задаче RenderHTML?

2022-07-05 19:27 UTC, bambruysk commented on cmd/server/http/handlers/metrics.go
> +	if err != nil {
Здесь стоит добавть логгирование. И вообще в этом пакете

2022-07-17 10:52 UTC, eridiumdev commented
Извиняюсь за большую задержку, наверное сейчас будет проще повторно пробежаться по коду, чем смотреть конкретные моменты.

Тем не менее, постарался учесть все комментарии, даю уточнения ниже.

1. Структура проекта
- добавил полное описание в README.md в корне репозитория
- структура приложения поменялась в корне (в т.ч. вследствие нашего вебинара по чистой архитектуре)
- в текущей итерации я подвинул интерфейсы поближе к тем, кто их использует, а не к тем, кто реализует
- оставил минимум кода в `cmd`, и основную часть вынес в пакет метрик `internal/metrics`

2. Go-шный стиль
- убрал префиксы `Get-` из методов типа `GetName()`
- сделал по-минимуму экспортируемых полей и структур, чтобы доступ был преимущественно по методам интерфейсов
- поменял названия интерфейсов, чтобы лучше отображать их суть (по этому пункту ремарка *2 ниже)
- настроил IDE для сортировки импортов в порядке stdlib -> external либы -> internal пакеты

3. Другое
- zerolog под капотом у логера. При этом я оставляю обертку над ним, чтобы энкапсулировать тот функционал, который нужен моему приложению, и не тащить стороннюю зависимость во все пакеты программы
- вынес общие настройки инициализации типов в структуры (AgentSettings/ServerSettings...)
- установил golangci-lint, некоторое время погоняю локально, потом добавлю в Github-actions

Ремарки:
```
func (st *InMemStorage) StoreMetric(metric metrics.Metric) error {
```
> Метод всегда будет возвращать пустую ошибку. С точки зрения языка ГО это является избыточной логикой. Если вы в данный момент не возвращаете ошибку, то стоит убрать из сигнатуры метода указание на ошибку как результат работы метода. Конечно, скорее всего вы предпологаете, что когда в будущем у вас будет другая логика работы, которая будет подразумевать наличие ошибка. Вот в момент времени, когда вы эту логику начнете реализовывать, тогда и добавьте указание на возвращаемое значение. А пока "мертвые хвосты" лучше отрубить.

Согласен, что повсеместно закладывать в интерфейс все гипотетические разветвления на все случаи жизни в будудущем излишне, но конкретно в данном примере с сохранием метрики я предчувствую, что в будущих спринтах мы перейдем на persistent-хранилище, и там без потенциальных error-ов не обойтись :) Но в целом, комментарий учел, постараюсь не перегружать интерфейсы, а итеративно наращивать функционал по необходимости.

```
	return TypeGauge
}

func (m GaugeMetric) GetValue() interface{} {
```
> Возвращать из функции пустой интерфейс не очень хорошо. Это нарушает типизацию, да и вообще не очень то принято.

Большую часть времени после ревью я потратил на попытки переделать приложение, в котором не было бы интерфейса Metric, а вместо него была бы структура. Но так и не смог прийти к какому-то решению, которое мне бы понравилось, и позволяло удобно работать с метрикой как с центральной сущностью приложения. Особенно, чтобы не приходилось повсеместно работать отдельно с MetricCounter, MetricGauge (...MetricX ?), создавать мапы на каждый тип и проч. Но возможно мой подход в корне не правилен, тут я не могу сказать (также на данном этапе не хотелось бы применять generics, а попробовать реализацию на vanilla Go)

Сюда же комментарий по поводу названия интерфейса `Metric`. Можно конечно обозвать `MetricHolder`, но опять же, учитывая что с этим придется работать повсеместно, хочется некой краткости в названии. Вдобавок, насколько я понимаю, интерфейсы с суффиксами `-er` (Reader, Writer) обычно выполняют ровно одну задачу, которая и заложена в сигнатуре интерфейса (Reader должен реализовать Read(), Writer - Write() и т.п.). Для комплексных сущностей мне кажется эта идиома не настолько форсирована.

2022-07-18 22:17 UTC, rktkov approved these changes
Было бы интересно посмотреть на компонентную схему решения. Если она существует, с удовольствием посмотрел бы, можно ссылку в личку в слаке кинуть.

2022-07-18 22:17 UTC, rktkov commented on internal/metrics/repository/in-mem.go
> +func (r *inMemRepo) Store(metric domain.Metric) error {
Очень смущают ошибки, которые всегда возвращаются равные nil. В этом методе и ниже.

2022-07-28 18:10 UTC, merged